{
 "title": "Kubernetes Deployment Metrics with GPU",
 "description": "Kubernetes Deployment Metrics with GPU\r\n\r\nMonitors Kubernetes deployments in cluster using Prometheus.\r\nShows overall cluster CPU / Memory of deployments, replicas in each deployment.\r\nUses Kube state metrics and cAdvisor metrics.\r\nhttps://github.com/dkozlov/grafana-kubernetes-gpu",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "Deployment",
    "query": "label_values(kube_deployment_labels{namespace=~\"$Namespace\"},deployment)"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_node_info, cluster)"
   },
   {
    "name": "Node",
    "query": "label_values(kube_node_info{cluster=\"$cluster\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$Namespace\", pod_name=~\"^$Deployment.*$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$Namespace\",deployment=~\"^$Deployment$\"}) / sum(kube_deployment_status_replicas{deployment=~\"^$Deployment$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{kubernetes_io_hostname=~\"^$Node.*$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$Namespace\",deployment=~\"^$Deployment$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$Namespace\",deployment=~\"^$Deployment$\"})"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"}[1m])) by (container_name, pod_name)",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"}[1m])) by (pod_name, name, image)",
     "legendFormat": "docker: {{ pod_name }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"}[1m])) by (pod_name, rkt_container_name)",
     "legendFormat": "rkt: {{ pod_name }} | {{ rkt_container_name }}"
    }
   ]
  },
  {
   "title": "Deployment GPU Duty Cycle usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "container_accelerator_duty_cycle{image!=\"\",name=~\"^k8s_.*\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"}",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Containers GPU Duty Cycle usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "container_accelerator_duty_cycle{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"} ",
     "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "container_accelerator_duty_cycle{image!=\"\",name!~\"^k8s_.*\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"} ",
     "legendFormat": "docker: {{ pod_name }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "container_accelerator_duty_cycle{rkt_container_name!=\"\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"} ",
     "legendFormat": "rkt: {{ pod_name }} | {{ rkt_container_name }}"
    }
   ]
  },
  {
   "title": "Deployment GPU Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "container_accelerator_memory_total_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"}\n",
     "legendFormat": "Total"
    },
    {
     "expr": "container_accelerator_memory_used_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"}\n",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Containers GPU Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decbytes", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "container_accelerator_memory_total_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"} ",
     "legendFormat": "Total: pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "container_accelerator_memory_total_bytes{image!=\"\",name!~\"^k8s_.*\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"} ",
     "legendFormat": "Total: docker: {{ pod_name }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "container_accelerator_memory_total_bytes{rkt_container_name!=\"\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"} ",
     "legendFormat": "Total: rkt: {{ pod_name }} | {{ rkt_container_name }}"
    },
    {
     "expr": "container_accelerator_memory_used_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"} ",
     "legendFormat": "Used: pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "container_accelerator_memory_used_bytes{image!=\"\",name!~\"^k8s_.*\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"} ",
     "legendFormat": "Used: pod: {{ pod_name }} | {{ container_name }}"
    },
    {
     "expr": "container_accelerator_memory_used_bytes{rkt_container_name!=\"\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"} ",
     "legendFormat": "Used: rkt: {{ pod_name }} | {{ rkt_container_name }}"
    }
   ]
  },
  {
   "title": "All processes CPU usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Deployment memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id!=\"/\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Deployment network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"}[1m])) by (pod_name)",
     "legendFormat": "Inbound: {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"}[1m])) by (pod_name)",
     "legendFormat": "Outbound: {{ pod_name }}"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"}[1m])) by (pod_name)",
     "legendFormat": "Inbound: {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",namespace=~\"$Namespace\",pod_name=~\"^$Deployment.*$\",node=~\"$Node\"}[1m])) by (pod_name)",
     "legendFormat": "Outbound: {{ pod_name }}"
    }
   ]
  }
 ]
}