apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
  - name: host-volume
    persistentVolumeClaim:
      claimName: pvc-smb
  containers:
  - image: busybox:1.24
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "touch /smbmount/SUCCESS && exit 0 || exit 1"]
    volumeMounts:
    - name: host-volume
      mountPath: "/smbmount"
