apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-dcgm-samba-pv-server
  namespace: monitoring-gpu
spec:
  storageClassName: grafana-dcgm-samba-server
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    #- dir_mode=0777
    #- file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    fsType: ext4
    volumeHandle: 4a68363a-a011-43cf-845f-f4ee0a0a84a0
  # make sure it's a unique id in the cluster,using kubectl describe csidrivers
    volumeAttributes:
      source: "//192.168.111.7/qzq"
    nodeStageSecretRef:
      name: "smbcreds"
      namespace: "default"
