apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus-dcgm-smb
provisioner: smb.csi.k8s.io
parameters:
  source: "//192.168.111.7/qzq"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "monitoring-gpu"
  createSubDir: "true"  # optional: create a sub dir for new volume
reclaimPolicy: Retain  # only retain is supported
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0775
  - file_mode=0775
  #- uid=1001
  #- gid=1001
