apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-dcgm-pvc-server
  namespace: monitoring-gpu
spec:
  storageClassName: grafana-dcgm-server
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce 
